### ISSUE TITLE
Bug: negative Ne estimates are returned in some cases

### ISSUE THREAD

**Issue by magicDGS** [ThomasTaus/poolSeq#1]
As pointed in Nest (https://github.com/ThomasTaus/Nest/issues/3), there is a bug in the returned value for Ne estimated to be negative. This should be fixed here or there, depending on the fate of the Nest original repository (see https://github.com/ThomasTaus/Nest/issues/1)

**Comment by ThomasTaus** [comment]
Dear Daniel,
thank you very much for your feedback. This issue will be addressed together with other performance improvements in the next [release](https://github.com/ThomasTaus/poolSeq/releases). For now I would ask you to convert negative values to positive infinity, as stated in the related [publication](http://www.genetics.org/content/204/2/723.long).
Cheers,
Thomas
